Changes made to make submit etc different
BitSaber/incy-io-kiosk-frontend pull request #130
Opened 2019-04-02 19:41 UTC by khenriksson

All my small changes regarding the design with the submit button and skip button looking different etc etc.

2019-04-03 08:55 UTC, VonLatvala requested changes
Scrollbars. Sec......

2019-04-03 09:23 UTC, VonLatvala submitted a review, later dismissed
Must say that I'm not a huge fan of the feint colors in select buttons (the ones you can toggle). But will leave the outlook design to you. When #132 is merged into this, I approve the changes.

2019-04-08 05:16 UTC, andersnylund requested changes

2019-04-08 05:16 UTC, andersnylund commented on src/components/FreeText.jsx
> +                        placeholder="Open feedback"
Shouldn't this placeholder be `<FormattedMessage id="textfield.placeholder" />` ?

2019-04-10 12:39 UTC, jallusparta requested changes
The multi select buttons shouldn't get wider when selected.

2019-04-10 12:41 UTC, jallusparta submitted a review, later dismissed
<img width="770" alt="Näyttökuva 2019-4-10 kello 15 40 23" src="https://user-images.githubusercontent.com/24315640/55879338-0b5fbb00-5ba7-11e9-8537-84baa1d9369b.png">

The placement of the text buttons to the middle, and some select buttons, doesn't work.

2019-04-10 12:45 UTC, jallusparta commented
> Must say that I'm not a huge fan of the feint colors in select buttons (the ones you can toggle). But will leave the outlook design to you. When #132 is merged into this, I approve the changes.

I agree with Axel on the colors of the multiselect buttons. I think send is okay neutral, but skip buttons color is too much of a different tone.

2019-04-10 17:32 UTC, tomrailio commented
4 shades of blue. Perhaps one too many.

2019-04-11 07:22 UTC, khenriksson commented
Then do you want me to change it to a completely different color? It's quite hard to find something that works with our other blue colors.

2019-04-14 10:49 UTC, khenriksson commented on src/components/FreeText.jsx
> +                        placeholder="Open feedback"
Not sure, changed it to that but gave me this
![image](https://user-images.githubusercontent.com/35761879/56091797-09a23a00-5ebc-11e9-9a7a-d8b5eea4eef4.png)

2019-04-14 16:14 UTC, VonLatvala approved these changes
Looks good, can't see finnish or swedish questions (application crash). But these changes don't introduce this problem.

2019-04-14 16:43 UTC, andersnylund approved these changes
Same as what @VonLatvala said, we have to fix the change language bug in develop, and preferably also #134, before merging

2019-04-14 17:59 UTC, merged