Progress bar color through prop
BitSaber/incy-io-kiosk-frontend pull request #133
Opened 2019-04-03 13:42 UTC by VonLatvala

Can be set by specifying `barColor` prop in `ProgressBar` component

2019-04-04 13:51 UTC, VonLatvala commented on src/components/App.jsx
> +                <ProgressBar barColor={'#2696fb'} />
don't fsckin hardcode

2019-04-08 05:11 UTC, andersnylund requested changes
On Chrome this works fine until the progress of the app reaches the The thank you page. There the progress bar is set back to the original darker blue color. 

And on Firefox the functionality breaks the app completely
<img width="1440" alt="Screenshot 2019-04-08 at 8 09 32" src="https://user-images.githubusercontent.com/18005239/55699938-cafd1300-59d5-11e9-96e1-6b5e070d88b1.png">

2019-04-10 17:55 UTC, VonLatvala commented
> On Chrome this works fine until the progress of the app reaches the The thank you page. There the progress bar is set back to the original darker blue color.
> 
> And on Firefox the functionality breaks the app completely
> <img alt="Screenshot 2019-04-08 at 8 09 32" width="1440" src="https://user-images.githubusercontent.com/18005239/55699938-cafd1300-59d5-11e9-96e1-6b5e070d88b1.png">

Firefox was never a target platform, but yeah..

2019-04-10 19:15 UTC, andersnylund approved these changes
Could the same be done with the circular progress bar?

2019-04-10 19:16 UTC, VonLatvala commented
> Could the same be done with the circular progress bar?

nope, not supported, support will be added in a later release

2019-04-10 19:16 UTC, merged

2019-04-10 19:39 UTC, VonLatvala commented
> Could the same be done with the circular progress bar?

Oh, sorry, yes, most probably, the same hack could be done to the circular one