Error page
BitSaber/incy-io-kiosk-frontend pull request #134
Opened 2019-04-10 12:57 UTC by valzugg

Should still do error handling for posting separately

![Capture](https://user-images.githubusercontent.com/33687905/55880273-07cd3380-5ba9-11e9-85b8-a3a6fbcbd989.PNG)

2019-04-10 16:07 UTC, andersnylund requested changes

2019-04-10 16:07 UTC, andersnylund commented on src/components/ErrorPage.jsx
> +    thankYouDiv: {
This came probably from ThankyouPage?

2019-04-10 16:07 UTC, andersnylund commented on src/translations/fi.json
> +    "error.message": "Virhe"
Would 'Jotakin meni pieleen' be better?

2019-04-10 16:07 UTC, andersnylund commented on src/translations/sv.json
> +    "error.message": "Fel"
'Någonting gick fel'

2019-04-10 17:00 UTC, VonLatvala commented on src/translations/sv.json
> +    "error.message": "Fel"
Or, ’homma kusi 🙉’ maybe?

2019-04-10 17:00 UTC, VonLatvala commented on src/translations/fi.json
> +    "error.message": "Virhe"
Or, ’homma kusi 🙉’, maybe?

2019-04-10 17:01 UTC, VonLatvala commented on src/translations/sv.json
> +    "error.message": "Fel"
Nåt gick snätt?

2019-04-14 08:16 UTC, andersnylund approved these changes

2019-04-14 17:59 UTC, merged